### ISSUE TITLE
[BUG] Opening note function has stopped working

### ISSUE THREAD

**Issue by psychsatani** [chrisgrieser/shimmering-obsidian#20]
Issue: I am unable to open notes all of a sudden. When I installed the latest version, it was working just fine. Then something snapped and other features like opening daily note and themes work but not the ability to see or open notes. 

### Debugging log:

[02:19:34.359] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[02:19:34.522] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[02:19:34.524] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/sharfaroz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C37FA2C6-89D2-402F-81A1-C16F4519689E/scripts/o_search.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)

I am on M1 Mac, 12.1 beta (21C5021h). Workflow version 2.0.2

**Comment by chrisgrieser** [comment]
So am I understanding this correctly: It *was* working at the beginning and then after a while it stopped working?

Could you check how many `.json` files are in the folder `{your-vault-path]/.obsidian/plugins/metadata-extractor`?

**Comment by psychsatani** [comment]
Only one is there. There are supposed to be 3. Reinstalled the plugin, still only 1 is there. How do I fix this?

**Comment by chrisgrieser** [comment]
In that case, you simply need to run `oupdate` → `Manually Refresh Metadata` once, so the metadata from the metadata-extractor plugin is available, which should solve the issue.

**Comment by psychsatani** [comment]
I did it. Now there are 4 json files but the issue persists.

**Comment by chrisgrieser** [comment]
Hmm, that's weird. Could you tell the filename of those 4 json files?

and make a brief screenshot of the settings page of the metadata-extractor plugin?

**Comment by psychsatani** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/78266798/140564552-e933ff33-3bf7-4335-9048-b775f8f1f072.png">

---
allExceptMd.json 
manifest.json 
metadata.json 
tags.json

**Comment by chrisgrieser** [comment]
Okay, now that the JSONs have been created, what does the debugging log show when you are running a search with `o something`?

**Comment by psychsatani** [comment]
[01:06:37.727] Logging Started...
[01:06:39.379] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[01:06:39.630] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[01:06:39.633] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/sharfaroz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.852BC082-F086-4793-A2E1-6749FCA2C064/scripts/o_search.js: execution error: Error: Error: find: : No such file or directory (1)

**Comment by chrisgrieser** [comment]
That's weird. When you open the workflow configuration, could you tell me what value has been assigned to `vault_path`?
<img width="135" alt="Screenshot 2021-11-05 20 43 29" src="https://user-images.githubusercontent.com/73286100/140569578-3548a3b9-cdb1-4416-b9a5-b23e5f0015a4.png">

**Comment by psychsatani** [comment]
So when I faced this issue, I reinstalled the workflow hoping that would fix it. But this time I forgot to add the vault path. I added the path and now it works as expected. Thanks a lot for patiently taking me through this!

**Comment by chrisgrieser** [comment]
no problem!

And yeah, with the way Alfred workflows work, re-installing them doesn't help much anyway in solving issues, which is why I also didn't add it to the trouble-shooting section :)

Btw, I would strongly recommend to configure the metadata extractor plugin to periodically write the metadata, [see here for further information](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Workflow%20Configuration.md#metadata-extractor-configuration).
