### ISSUE TITLE
[Bug]: Cannot search contents

### ISSUE THREAD

**Issue by amree** [chrisgrieser/shimmering-obsidian#60]
### Bug Description

I can't search the content of my notes

### Relevant Screenshot

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/424392/155307548-0d840bf0-7c79-4fe9-bf64-c70b0a30a4c6.png">

### To Reproduce

1. Open Alfred
2. Type "o", space, "largest"
3. No result found

### Debugging Log

```Text
[19:06:48.345] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[19:06:48.522] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[19:06:48.524] Shimmering Obsidian[Script Filter] {"items":[{"title":"🕑 Linux","match":"Linux Linux filename name title","subtitle":"▸ Cheatsheets","arg":"Cheatsheets/Linux.md","quicklookurl":"/Users/amree/Library/Mobile Documents/iCloud~md~obsidian/Documents/Personal/Cheatsheets/Linux.md","type":"file:skipcheck","uid":"Cheatsheets/Linux.md","icon":{"path":"icons/note.png"},"mods":{"shift":{"valid":false,"subtitle":"⛔️ Note without Outgoing Links or Backlinks"}}},{"title":"Cheatsheets","match":"Cheatsheets Cheatsheets folder","subtitle":"▸ /   [↵: Browse]","arg":"Cheatsheets","type":"file:skipcheck","uid":"Cheatsheets","icon":{"path":"icons/folder.png"},"mods":{"alt":{"subtitle":"⌥: Open Folder in Finder"},"cmd":{"valid":false,"subtitle":"⛔️ Cannot open folders"},"shift":{"valid":false,"subtitle":"⛔️ Folders have no links."},"ctrl":{"valid":false,"subtitle":"⛔️ Linking not possible for folders"},"fn":{"valid":false,"subtitle":"⛔️ Cannot append to folders."}}}]}
```

### Workflow Configuration

![image](https://user-images.githubusercontent.com/424392/155308015-5bfb075c-c243-4464-82c9-0a1adddd19aa.png)

### Version & System Information

I got errors running that command:

```Text
[19:09:35.464] Shimmering Obsidian[Keyword] Processing complete
[19:09:35.466] Shimmering Obsidian[Keyword] Passing output '' to Run Script
[19:09:35.605] ERROR: Shimmering Obsidian[Run Script] /Users/amree/Dropbox/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95/scripts/version_info.js: execution error: Error: Error: ls: *.asar: No such file or directory (1)
[19:09:35.609] Shimmering Obsidian[Run Script] Processing complete
[19:09:35.610] Shimmering Obsidian[Run Script] Passing output '' to Copy to Clipboard
[19:09:35.611] Shimmering Obsidian[Copy to Clipboard] Processing complete
[19:09:35.612] Shimmering Obsidian[Copy to Clipboard] Passing output '' to Post Notification
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
I fixed the issue with `oinfo` in release 2.21.5, could you try running it again?

if it does not work, could you go into the folder `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Personal/.obsidian/plugins/metadata-extractor/` and list all files that are present there?

**Comment by amree** [comment]
@chrisgrieser 

`oinfo` worked this time. But the search still doesn't work

```
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.2.1
Obsidian: .asar file missing
Alfred: 4.6.3
Workflow: 2.21.5
Advanced URI Plugin: 1.17.0
Metadata Extractor: 1.0.0
-------------------------------
LATEST VERSION
Obsidian: 0.13.23
Obsidian (Insider): 0.13.26
Workflow: 2.21.5
Advanced URI Plugin: 1.17.0
Metadata Extractor: 1.0.0
-------------------------------
```

**Comment by amree** [comment]
List of files

```
~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Personal/.obsidian/plugins/metadata-extractor                                                                                                                                                                                                                                                           10:17:23 PM
❯ l
total 72
drwxr-xr-x@ 8 amree  staff   256B Feb 23 19:53 .
drwxr-xr-x@ 4 amree  staff   128B Feb 23 19:53 ..
-rw-r--r--  1 amree  staff   156B Feb 23 21:24 allExceptMd.json
-rw-r--r--@ 1 amree  staff   249B Feb 23 19:53 data.json
-rw-r--r--  1 amree  staff    13K Feb 23 19:47 main.js
-rw-r--r--  1 amree  staff   326B Feb 23 19:47 manifest.json
-rw-r--r--  1 amree  staff    79B Feb 23 21:24 metadata.json
-rw-r--r--  1 amree  staff   108B Feb 23 19:50 tags.json
```

**Comment by chrisgrieser** [comment]
hmm, that looks like an issue with the metadata. Could you run `oupdate` ➞ `Update Workflow Functions` ➞ `Manually update Metadata` and see if the issue persists?

**Comment by amree** [comment]
I did that and it still doesn't work. Here is the log:

```
[22:19:40.788] Shimmering Obsidian[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E5FECA0A1-6B1F-419D-8159-77F3A96C540F)] Queuing argument '(null)'
[22:19:41.003] Shimmering Obsidian[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E5FECA0A1-6B1F-419D-8159-77F3A96C540F)] Script with argv '(null)' finished
[22:19:41.005] Shimmering Obsidian[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E5FECA0A1-6B1F-419D-8159-77F3A96C540F)] {"items":[{"title":"🕑 Linux","match":"Linux Linux filename name title","subtitle":"▸ Cheatsheets","arg":"Cheatsheets/Linux.md","quicklookurl":"/Users/amree/Library/Mobile Documents/iCloud~md~obsidian/Documents/Personal/Cheatsheets/Linux.md","type":"file:skipcheck","uid":"Cheatsheets/Linux.md","icon":{"path":"icons/note.png"},"mods":{"shift":{"valid":false,"subtitle":"⛔️ Note without Outgoing Links or Backlinks"}}},{"title":"Cheatsheets","match":"Cheatsheets Cheatsheets folder","subtitle":"▸ /   [↵: Browse]","arg":"Cheatsheets","type":"file:skipcheck","uid":"Cheatsheets","icon":{"path":"icons/folder.png"},"mods":{"alt":{"subtitle":"⌥: Open Folder in Finder"},"cmd":{"valid":false,"subtitle":"⛔️ Cannot open folders"},"shift":{"valid":false,"subtitle":"⛔️ Folders have no links."},"ctrl":{"valid":false,"subtitle":"⛔️ Linking not possible for folders"},"fn":{"valid":false,"subtitle":"⛔️ Cannot append to folders."}}}]}
[22:19:47.122] Shimmering Obsidian[[List Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E8A0787B6-CC86-4694-BB26-C626130438BE)] Processing complete
[22:19:47.124] Shimmering Obsidian[[List Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E8A0787B6-CC86-4694-BB26-C626130438BE)] Passing output 'manual_metadata' to [Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEF69BC31-CD56-49CC-9172-A3EE6940DDD3)
[22:19:47.125] Shimmering Obsidian[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEF69BC31-CD56-49CC-9172-A3EE6940DDD3)] Processing complete
[22:19:47.125] Shimmering Obsidian[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEF69BC31-CD56-49CC-9172-A3EE6940DDD3)] Passing output 'manual_metadata' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEC424B98-D702-4608-B1EA-07AF49C56048)
[22:19:49.538] Shimmering Obsidian[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEC424B98-D702-4608-B1EA-07AF49C56048)] Processing complete
[22:19:49.541] Shimmering Obsidian[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEC424B98-D702-4608-B1EA-07AF49C56048)] Passing output '' to [Post Notification](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E099D27EE-A12C-4248-B4EC-C46C34F5415E)
[22:19:49.543] Shimmering Obsidian[[Post Notification](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E099D27EE-A12C-4248-B4EC-C46C34F5415E)] Processing complete
[22:19:49.543] Shimmering Obsidian[[Post Notification](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E099D27EE-A12C-4248-B4EC-C46C34F5415E)] Passing output '' to [Play Sound](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E2FD866C2-DDB1-4C2D-A420-3A580FBC60D2)
[22:19:49.620] Shimmering Obsidian[[Play Sound](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E2FD866C2-DDB1-4C2D-A420-3A580FBC60D2)] Processing complete
[22:19:49.621] Shimmering Obsidian[[Play Sound](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E2FD866C2-DDB1-4C2D-A420-3A580FBC60D2)] Passing output '' to [Call External Trigger](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3E5C1918E9-6508-4076-8D79-716B47ACFC20)
[22:19:49.627] Shimmering Obsidian[[External](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EE7DAD30E-15A3-46BE-8534-7F5ABE826FC6)] Processing complete
[22:19:49.628] Shimmering Obsidian[[External](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EE7DAD30E-15A3-46BE-8534-7F5ABE826FC6)] Passing output '' to [Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEDD0CFEF-63C0-4BD0-8E9E-4BD5B43D92DD)
[22:19:49.629] Shimmering Obsidian[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEDD0CFEF-63C0-4BD0-8E9E-4BD5B43D92DD)] Processing complete
[22:19:49.629] Shimmering Obsidian[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EEDD0CFEF-63C0-4BD0-8E9E-4BD5B43D92DD)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.468D48BE-7536-447E-A31E-4E81F1D4FE95%3EB0B1C61B-93A6-492E-BD07-2F06FB73F410)
```

**Comment by chrisgrieser** [comment]
ah wait, now I am noticing. You are searching for "largest", which is not the name of the file.

The `o...` search only searches for file names and aliases (and if enabled headings) and tags, but it does not search the full contents of the file

**Comment by amree** [comment]
Uh. I assumed I can search by the contents. Is that not possible? I'll check the doc as well
