### ISSUE TITLE
[Bug]: scratchpad_append_prefix doesn't pass datetime placeholder

### ISSUE THREAD

**Issue by iys32164** [chrisgrieser/shimmering-obsidian#75]
### Bug Description

At the moment I setup the workflow for my first vault, scratchpad_append_prefix properly passed datetime using dynamic placeholder.
After I setup second vault, appending a text to scratchpad fails to write datetime for both vaults.
Meanwhile, 'append_prefix' and 'daily_note_append_prefix' still work well. 

Result in the scratchpad file looks like:

**(2022-04-30, 05:46)** via o, fn+enter, manual, while debugging
**({date:yyyy-MM-dd}, {time:HH:mm})** via oo, while debugging

### Debugging Log

```Text
[05:46:03.651] Shimmering Obsidian[Script Filter] Processing complete
[05:46:03.662] Shimmering Obsidian[Script Filter] Passing output 'Instant.md' to Call External Trigger
[05:46:03.665] Shimmering Obsidian[External] Processing complete
[05:46:03.667] Shimmering Obsidian[External] Passing output 'Instant.md' to Arg and Vars
[05:46:03.669] Shimmering Obsidian[Arg and Vars] Processing complete
[05:46:03.671] Shimmering Obsidian[Arg and Vars] Passing output '' to Conditional
[05:46:03.673] Shimmering Obsidian[Conditional] Processing complete
[05:46:03.675] Shimmering Obsidian[Conditional] Passing output '' to Keyword
[05:46:24.887] Shimmering Obsidian[Keyword] Processing complete
[05:46:24.890] Shimmering Obsidian[Keyword] Passing output 'via o, fn+enter, manual, while debugging' to Write Text File
[05:46:24.893] Shimmering Obsidian[Write Text File] Processing complete
[05:46:24.896] Shimmering Obsidian[Write Text File] Passing output '/Users/ysim/Library/CloudStorage/OneDrive-개인/Journals/Instant.md' to Conditional
[05:46:24.898] Shimmering Obsidian[Conditional] Processing complete
[05:46:24.900] Shimmering Obsidian[Conditional] Passing output '/Users/ysim/Library/CloudStorage/OneDrive-개인/Journals/Instant.md' to Post Notification
[05:46:40.864] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[05:47:06.697] Shimmering Obsidian[Keyword] Processing complete
[05:47:06.700] Shimmering Obsidian[Keyword] Passing output 'via oo, while debugging' to Arg and Vars
[05:47:06.702] Shimmering Obsidian[Arg and Vars] Processing complete
[05:47:06.704] Shimmering Obsidian[Arg and Vars] Passing output 'via oo, while debugging' to Run Script
[05:47:06.874] Shimmering Obsidian[Run Script] Processing complete
[05:47:06.890] Shimmering Obsidian[Run Script] Passing output 'Instant
' to Conditional
[05:47:06.893] Shimmering Obsidian[Conditional] Processing complete
[05:47:06.895] Shimmering Obsidian[Conditional] Passing output 'Instant
' to Post Notification
```

### Workflow Configuration

<img width="1292" alt="스크린샷 2022-04-30 오전 6 03 34" src="https://user-images.githubusercontent.com/58249051/166069084-2b06c2eb-153a-4395-9791-fe3959fddea1.png">

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.3.1
Alfred: 4.6.5

Obsidian: .asar file missing
This Workflow: 2.22.6
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.1
-------------------------------
LATEST VERSION
Obsidian: 0.14.6 (Insider: 0.14.7)
This Workflow: 2.22.6
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.1
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by saxasmu** [comment]
I have same issue:
scratchpad_append_prefix does NOT pass daytime but ocr_prefix does!

**Comment by bramses** [comment]
Facing a similar issue w/
<img width="423" alt="Screen Shot 2022-07-16 at 8 24 03 PM" src="https://user-images.githubusercontent.com/3282661/179380062-b4fc8a1f-1dc6-48cf-9401-d1b94b6aa639.png">

**Comment by gtewary1** [comment]
Is there no fix for this issue yet?

**Comment by chrisgrieser** [comment]
Hi, sorry I didn't have much time to work on this, since I had to look after a lot of other issues (like a complete rewrite of my theme due to Obsidian 1.0).


Should be fixed now.

**Comment by joshsarvesh** [comment]
Was this actually fixed? For me this still doesn't work in V3.3.3. 
By the way, there are user variables and environment variables where scratchpad_append_prefix shows. Environment variable scratchpad_append_prefix has no effect on the behavior and user variable seems to over-ride the environment variable values and user variable doesn't support datetime placeholder. 


![image](https://user-images.githubusercontent.com/32550224/210662708-4c5bc856-3bcf-4209-aed9-21d0ecf7d9eb.png)

**Comment by chrisgrieser** [comment]
Please open a new bug report if this isn't fixed for you, the form asks for various kinds of information I need to be able to do anything about it
